stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build:
  stage: build
  before_script:
    - cp ${ENV} .env
    - cp ${TEST_ENV} .env_test
  script:
    - echo "Starting build-job..."
    - docker build -t booking-api-image .

lint:
  stage: test
  script:
    - docker run --rm booking-api-image ruff check

format-check:
  stage: test
  script:
    - docker run --rm booking-api-image ruff format --check

pytest:
  stage: test
  script:
    - docker compose --file docker-compose-api.yml run booking_back pytest -s -vv

deploy:
  stage: deploy
  before_script:
    - cp ${ENV} .env
  script:
    - echo "Deploying application..."
    - docker compose --file docker-compose-api.yml up -d
    - docker compose exec booking_nginx nginx -s reload
    - echo "Application successfully deployed."
